# Action 的名字
name: Hexo Auto Deploy

on:
  # 触发条件1：main 分支收到 push 后执行任务。
  push:
  workflow_dispatch:

# 这里放环境变量,需要替换成你自己的
env:
  # Hexo 编译后使用此 git 用户部署到 github 仓库
  GIT_USER: KheshigFleet
  # Hexo 编译后使用此 git 邮箱部署到 github 仓库
  GIT_EMAIL: gwodin@163.com
  # Hexo 编译后要部署的 github 仓库
  GIT_DEPLOY_REPO: KheshigFleet/KheshigFleet.github.io
  # Hexo 编译后要部署到的分支
  GIT_DEPLOY_BRANCH: main

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node_version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GIT_DEPLOY_REPO }}
          ref: ${{ env.GIT_DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

